INSERT INTO holodome.usuario (id,nome,email) VALUES 
(1,'Brevage Luck','sameemail@sameemail.com')
,(2,'Aladdin','sameemail@sameemail.com')
,(3,'Scar','sameemail@sameemail.com')
,(4,'Naia','sameemail@sameemail.com')
,(5,'Pumba','sameemail@sameemail.com')
,(6,'Simba','sameemail@sameemail.com')
,(7,'Timão','sameemail@sameemail.com')
,(8,'poh','sameemail@sameemail.com')
,(9,'lala','sameemail@sameemail.com')
,(10,'wink','sameemail@sameemail.com')
;
INSERT INTO holodome.usuario (id,nome,email) VALUES 
(11,'dink','sameemail@sameemail.com')
,(12,'Drogo','sameemail@sameemail.com')
,(13,'João das Neves','sameemail@sameemail.com')
,(14,'Melissa','sameemail@sameemail.com')
,(15,'Craudio','sameemail@sameemail.com')
,(16,'Dino','sameemail@sameemail.com')
,(17,'Tequila Luck','sameemail@sameemail.com')
,(18,'Bino','sameemail@sameemail.com')
,(19,'Don Draper','sameemail@sameemail.com')
,(20,'Clark','sameemail@sameemail.com')
;
INSERT INTO holodome.usuario (id,nome,email) VALUES 
(21,'Hipolita','sameemail@sameemail.com')
,(22,'Demeter','sameemail@sameemail.com')
,(23,'Hades','sameemail@sameemail.com')
,(24,'Poseidon','sameemail@sameemail.com')
,(25,'Zeus','sameemail@sameemail.com')
,(26,'Vodka Luck','sameemail@sameemail.com')
,(27,'Rubbick','sameemail@sameemail.com')
,(28,'Ray','sameemail@sameemail.com')
,(29,'Solar gun','sameemail@sameemail.com')
,(30,'Tempest','sameemail@sameemail.com')
;
INSERT INTO holodome.usuario (id,nome,email) VALUES 
(31,'Adam Warlock','sameemail@sameemail.com')
,(32,'Rum Luck','sameemail@sameemail.com')
,(33,'Lucy','sameemail@sameemail.com')
,(34,'Salamander','sameemail@sameemail.com')
,(35,'Wendy','sameemail@sameemail.com')
,(36,'Uwendel','sameemail@sameemail.com')
,(37,'carol','sameemail@sameemail.com')
,(38,'carolina','sameemail@sameemail.com')
,(39,'caroline','sameemail@sameemail.com')
,(40,'ana tatian','sameemail@sameemail.com')
;
INSERT INTO holodome.usuario (id,nome,email) VALUES 
(41,'amanda','sameemail@sameemail.com')
,(42,'Brain puck','sameemail@sameemail.com')
,(43,'Bruno zuck','sameemail@sameemail.com')
,(44,'Breno buck','sameemail@sameemail.com')
,(45,'Brian Luck','sameemail@sameemail.com')
,(46,'Ana Luiza','sameemail@sameemail.com')
,(47,'Beatriz Luara','sameemail@sameemail.com')
,(48,'Sussan Velican','sameemail@sameemail.com')
,(49,'Rebecca Lucky','sameemail@sameemail.com')
,(50,'Gin Luck','sameemail@sameemail.com')
;